### ISSUE TITLE
Show the output of computed log

### ISSUE THREAD

**Issue by ashryanbeats** [AdobeXD/plugin-docs#10]
# Submit an issue

## Topic

This is an issue regarding:

- [x] The guides contained within this repo.

## Description of the issue

Revise:

```javascript
console.log("el fill color =" + el.fill);
```

to:

```javascript
console.log("el fill color =" + el.fill); // OUTPUT HERE
```

**Comment by peterflynn** [comment]
👍, we try to do this in most of the XD docs (scenegraph, renditions, etc.) already.

**Comment by dkstevekwak** [comment]
@ErinFinnegan could you add the output as mentioned above to your debugging guide?
Ref: https://adobexdplatform.com/plugin-docs/tutorials/debugging/?h=el.fill
