### ISSUE TITLE
Next arrow button on specific page doesn't go anywhere

### ISSUE THREAD

**Issue by timkim** [AdobeXD/plugin-docs#150]
# Submit an issue

## Topic
The next arrow button on this page:
[https://adobexdplatform.com/plugin-docs/reference/how-to-read.html](https://adobexdplatform.com/plugin-docs/reference/how-to-read.html)
does not go anywhere. 
<img width="1328" alt="screen shot 2018-11-20 at 10 52 56 am" src="https://user-images.githubusercontent.com/57922/48795741-956bbd80-ecb2-11e8-9c58-bcfc38afc92b.png">

This is an issue regarding:

- [x] The tutorials contained within this repo.
- [ ] The samples contained within this repo.

## Versions
Current version of the site. 

## Description of the issue
I noticed that the right arrow to go to the next article just points back to itself:
```
<a href="how-to-read.html" class="navigation navigation-next " aria-label="Next page: How to read this reference" style="margin-right: 0px;">
  <i class="fa fa-angle-right"></i>
</a>
```

## Proposed solution or attempted solutions that failed
<img width="250" alt="screen shot 2018-11-20 at 10 56 56 am" src="https://user-images.githubusercontent.com/57922/48795906-0a3ef780-ecb3-11e8-9f72-72b7fe31938d.png">

I think the root of the issue is that these two items are the same page. My guess is that whatever generated the doc saw that the next link is itself instead of [https://adobexdplatform.com/plugin-docs/reference/application.html](https://adobexdplatform.com/plugin-docs/reference/application.html)

**Comment by dkstevekwak** [comment]
@kerrishotts could you look at this when you have time? I was able to replicate the behavior. This is probably related to Gitbook issues and the proposed solution by @timkim seems reasonable.

**Comment by ashryanbeats** [comment]
Looks like this has since been addressed. Thank you!
