### ISSUE TITLE
Typo in sample code in uxp-variant of button

### ISSUE THREAD

**Issue by yoshikinoko** [AdobeXD/plugin-docs#153]
# Submit an issue

## Topic

This is an issue regarding:

- [ ] The tutorials contained within this repo.
- [x] The samples contained within this repo.

## Versions

- [ ] Supported XD version(s):

## Description of the issue

`Cancel`is used in sample code, but `Delete` is displayed in the resulting image.

[website](https://adobexdplatform.com/plugin-docs/reference/ui/elements/buttons.html#variantwarning) 
[git repo](https://github.com/AdobeXD/plugin-docs/blob/313b266e892c93c15beff15d61d67e0677d1e86b/reference/ui/elements/buttons.md
)

![result image](https://raw.githubusercontent.com/AdobeXD/plugin-docs/313b266e892c93c15beff15d61d67e0677d1e86b/reference/ui/assets/button-variant-warning.png)

## Proposed solution or attempted solutions that failed

update the code 

https://github.com/AdobeXD/plugin-docs/blame/master/reference/ui/elements/buttons.md#L112-L115

```html
<button uxp-variant="warning">Delete</button>
<button uxp-variant="warning" uxp-quiet="true">Delete</button>
```

**Comment by dkstevekwak** [comment]
@yoshikinoko thanks for catching this. addressed - b3c7d438658bd0be3d265bb3322ddccaf530a294
