### ISSUE TITLE
typo in ui-index.md witht 

### ISSUE THREAD

**Issue by mihiramin89** [AdobeXD/plugin-docs#167]
# Submit an issue

## Topic

This is an issue regarding:

- [x] The tutorials contained within this repo.
- [ ] The samples contained within this repo.

## Versions

- [ ] Supported XD version(s):

## Description of the issue
- There is a typo in the ui-index.md file.

## Proposed solution or attempted solutions that failed
- `witht` --> `with`

**Comment by dkstevekwak** [comment]
@mihiramin89 thanks for catching this. PR referenced above addresses this issue
