### ISSUE TITLE
SceneNode::pluginData: * read-only?

### ISSUE THREAD

**Issue by pklaschka** [AdobeXD/plugin-docs#170]
# Submit an issue

## Topic

This is an issue regarding:

- [x] The tutorials contained within this repo.
- [ ] The samples contained within this repo.

## Versions

- [x] Supported XD version(s): 14

## Description of the issue
`SceneNode::pluginData: *` reads as read-only, although it makes no sense that it is (leaving me to believe it's a typo)

## Proposed solution or attempted solutions that failed
Remove read-only in reference/scenegraph.md => sceneNode.pluginData (https://github.com/AdobeXD/plugin-docs/blob/master/reference/scenegraph.md#scenenodeplugindata--)

**Comment by peterflynn** [comment]
Fixed
