### ISSUE TITLE
Typos in beginner tutorials

### ISSUE THREAD

**Issue by lukexjeremy** [AdobeXD/plugin-docs#172]
# Submit an issue

## Topic

This is an issue regarding:

- [x] The tutorials contained within this repo.
- [ ] The samples contained within this repo.

## Versions

- [ ] Supported XD version(s):

## Description of the issue
Typos

## Proposed solution or attempted solutions that failed

| File | Written | Proposed Correction |
|-----|----------|------------------------|
|how-to-work-with-scenenodelist.md|ellispses|ellipses|
|how-to-draw-lines.md|assing|assigning|
||||

**Comment by dkstevekwak** [comment]
@lukexjeremy thanks for reporting the issue. I have fixed the reported typos.
https://github.com/AdobeXD/plugin-docs/commit/0c06b7463e35103f8008eab1a9968e6189fd76bc
