### ISSUE TITLE
How to use Blob in plugin

### ISSUE THREAD

**Issue by walkingxian** [AdobeXD/plugin-docs#184]
# Submit an issue

## Topic

This is an issue regarding:

- [ ] The tutorials contained within this repo.
- [ ] The samples contained within this repo.

## Versions

- [ ] Supported XD version(s):

**Comment by dkstevekwak** [comment]
Blob support is labeled as "coming soon" in the [XD extensibility roadmap](https://trello.com/c/PkMZ20p3/22-blob-support). Please stay tuned!

**Comment by nigelthinksprint** [comment]
has this been released? Everyone has said just work with the returned ArrayBuffer. But today with graphQL is fairly hard to work with arrayBuffer.

So the Trello roadmap claims it was put in "Released" Back in 2019 July? What's the deal is it actually or are these things totally forgotten about?

![image](https://user-images.githubusercontent.com/43784132/89951269-068b9b00-dc23-11ea-9b74-a5a98c175519.png)

I get the javascript engine probably has some technical limitations when running in Adobe XD but some of these fairly common native APIs that still haven't been polyfilled is really limiting.
