### ISSUE TITLE
SymbolInstance::isMaster boolean or string?

### ISSUE THREAD

**Issue by pklaschka** [AdobeXD/plugin-docs#196]
# Submit an issue

## Topic

This is an issue regarding:

- [x] The tutorials contained within this repo.
- [ ] The samples contained within this repo.

## Versions

- [ ] Supported XD version(s):

## Description of the issue
Currently, the read-only property `isMaster` of `SymbolInstance` is (in its documentation – not in the index above) specified as a `string`. However, this makes no sense and also, all other occurrences denote its type as `boolean` (which – of course – makes sense). Therefore, the docs seem to be wrong there.

## Proposed solution or attempted solutions that failed
Change that line from `string` to `boolean`

**Comment by peterflynn** [comment]
Yep, it should say `boolean`. Will fix.

**Comment by dkstevekwak** [comment]
@pklaschka thanks for reporting this. Fixed by c5851edea4c4d633ae54d06512ba4a6427c4c354
CC: @peterflynn
