### ISSUE TITLE
Broken link on index page of XD specifics APIs

### ISSUE THREAD

**Issue by yoshikinoko** [AdobeXD/plugin-docs#209]
# Submit an issue

## Topic

This is an issue regarding:

- [x] The tutorials contained within this repo.
- [ ] The samples contained within this repo.

## Versions

- [ ] Supported XD version(s):
N/A

## Description of the issue

Borken link for viewport.md
https://github.com/AdobeXD/plugin-docs/blame/master/reference/xd-index.md#L12
```
- [viewport](/reference/ciewport.md)
```

## Proposed solution or attempted solutions that failed

```
- [viewport](/reference/viewport.md)
```

**Comment by ashryanbeats** [comment]
Looks like this one was addressed in a PR a while back. Thanks!
