### ISSUE TITLE
Add link to sign up for the CC Developer Newsletter on the Community page

### ISSUE THREAD

**Issue by ashryanbeats** [AdobeXD/plugin-docs#23]
# Submit an issue

## Topic

This is an issue regarding:

- [x] The guides contained within this repo.

## Description of the issue
[Dependency] Fixing the signup page.

**Comment by dkstevekwak** [comment]
@ErinFinnegan Can you provide me the link? I will add it on the community page

**Comment by ErinFinnegan** [comment]
https://www.adobe.com/subscription/ccdevnewsletter.html
