### ISSUE TITLE
Review all relative links in /Guides/getting-started-guide

### ISSUE THREAD

**Issue by ashryanbeats** [AdobeXD/plugin-docs#5]
# Submit an issue

## Topic

This is an issue regarding:

- [x] The guides contained within this repo.
- [ ] The samples contained within this repo.

## Versions

- [ ] Supported XD version(s):

**Comment by filmaj** [comment]
@ashryanbeats may I ask why this was done?

I am doing some work to see about hosting these docs under e.g. a future adobe developer site 😇

**Comment by ashryanbeats** [comment]
Hi Fil, 

Trying to jog my memory here... I think it was just about how the links worked during the long pre-launch period when building locally was required. 

I don’t believe we’re using absolute links. If we are anywhere, I bet it’s an oversight.

On my phone, but can look into it more if you’ve got specific questions. 

- Ash

**Comment by filmaj** [comment]
I just noticed some absolute links in the README in this repo (e.g. the quickstart tutorial and other tutorial links in the opening paragraphs of the README).

The reason I ask was I was putting up a staging environment with the e.g. XD plugin docs hosted under a subdirectory on a domain, kind of testing out how a future developer portal site would work (with different content being pulled in from different repos on github, mapped to different paths/subdirectories on the site). Absolute links ruin the ability to "prefix" the docs into a specific subdirectory, thus why I was wondering if using absolute links were serving a specific for y'all.

If this is not required, I am happy to send a PR fixing absolute to relative links, which shouldn't break anything on e.g. github pages or other hosted sites, but also help us with hosting the docs on other properties 😄

**Comment by ashryanbeats** [comment]
Absolute links for on-site pages are not a requirement for us, and it's our intention to avoid them.

Taking the readme, that you mention, as an example:
https://raw.githubusercontent.com/AdobeXD/plugin-docs/master/README.md

I'm not seeing where we're using absolute links for on-site pages. Unless you're asking us to explicitly include the path segment (`.` or `..`) in relative links, I'll need you to point me to a specific example of what we're doing that you want us to change.

There _are_ a number of absolute links in the readme and throughout the site, but those are "off-site" links pointing to, in the case of the top-level readme:

- `adobe.com`
- `github.com`

The GitHub links are intentionally absolute, because they aren't pointing the reader to a rendered page of docs, but an actual repo on GitHub (i.e., the reader leaves the docs site to go see a repo on github.com).

Examples:

- `[sample plugins](https://github.com/AdobeXD/plugin-samples)`
- `[ui-hello-react](https://github.com/AdobeXD/plugin-samples/tree/master/ui-hello-react)`

***

Based on the above info, is there still an issue? If so, can you point me to a specific line of markdown, and show me what the change would look like?

**Comment by filmaj** [comment]
You can't see it on github's preview or github's rendered markdown, but if you go to this raw link:

https://raw.githubusercontent.com/AdobeXD/plugin-docs/master/README.md

then search for `](/`, I see 12 links that are absolute - that start with a leading slash:

```
[Quick Start tutorial](/tutorials/quick-start)
```

Would it be OK to change these links so that they either start with a dot, or drop the leading slash? So the above example would turn into:

```
[Quick Start tutorial](./tutorials/quick-start)
```

or

```
[Quick Start tutorial](tutorials/quick-start)
```

**Comment by ashryanbeats** [comment]
Ah ha! Yep, this stuff should be fine to change (as long as GitBook jibes with it), and is admittedly haphazard at the moment. 

We did a quick sweep on all links the morning before MAX to make sure things would work on the live site, so consistency fell by the wayside.

Please note that we have a big branch to merge and push soon, so if you do submit a PR on this, we'll need to wait until after that to merge your PR. Just aiming not to rock the boat too much at once.

Let me know if you need anything from me.

**Comment by filmaj** [comment]
Great! I'll watch the repo for that big PR and put together a PR of my own once that lands. I shouldn't need anything from you other than a review of my PR down the road 😄
