### ISSUE TITLE
Image in /Guides/debugging-guide

### ISSUE THREAD

**Issue by ashryanbeats** [AdobeXD/plugin-docs#8]
# Submit an issue

## Topic

This is an issue regarding:

- [x] The guides contained within this repo.

## Description of the issue
Given the placement of `/images/readme-assets/reload-plugins.png`, perhaps it should show a plugin loading error?

**Comment by dkstevekwak** [comment]
Agreed with Ash. @ErinFinnegan could you replace the image with an actual error being logged please?

**Comment by ErinFinnegan** [comment]
OK, I uploaded a new image showing an actual error here: https://github.com/AdobeXD/plugin-docs/blob/master/images/reload-error.png

Is that what you were going for?
